### ISSUE TITLE
Set widget properties remotely

### ISSUE THREAD

**Issue by digitalwannabe** [charlieroberts/interface.server.2#1]
hi,

i'm looking for a browser alternative for the lemur iOS app and interface.js looks very promising! I've seen in v2 you can set some settings for your app remotely, now i wonder, is it possible to create/delete widgets dynamically as well as set widget properties remotely, like widget name, color, menu entries?
The lemur interface I'm trying to replicate in the browser does accept osc messages to do all that, so osc is bi-directional, which allows me to dynamically change part of my interface according to my situation.

Is behaviour similar to that supported by interface.js?  If not, would it be hard to implement and can you @charlieroberts maybe point me in the right direction? (not super experienced in js but i think i can work this out...)

As I intend to run the interface server on the same pc as the app i want to control (vvvv) runs on, I understand one workaround could be to edit the html for the interface directly, but this would require refreshing, correct?

thank you

**Comment by charlieroberts** [comment]
Hello,

There aren't always direct OSC callbacks pointing to these properties, but you can register a generic OSC callback that should let you do whatever you want, [here's an example]( https://github.com/charlieroberts/interface.js/blob/master/server/interfaces/OSC_test.htm)

Here's a video: https://vimeo.com/61315008

There's been some fancier work on this, but I'm not sure everything is up-to-date... that would require some testing / experimentation. I'll try and look into it. However, can you open up this issue in the interface.js repo instead? I'm going to close it here. The naming is a bit confusing, but this repo is for a much bigger project that handles HID, MIDI, and a bunch of other stuff in addition web-based interfaces.

And just in case you're interested, here's a video doing cool stuff using a precursor to interface.js that was a mobile app: https://vimeo.com/37297453
